export const TRACKER_STRINGS = {
  todayPrefix: "Today",
  completedSummary: (done: number, max: number) => `${done} / ${max} completed`,
  retry: "Retry",
  goToLogin: "Go to login",
  completedForToday: "Completed for today",
  moreAvailable: (n: number) => `${n} more available today`,
  notStarted: "Not started today",
  undo: "Undo",
  markDone: "Mark done",
  done: "Done",
  busyEllipsis: "…",
  sessionsSummary: (done: number, max: number) => `${done}/${max} sessions`,
  goalTitle: "Today's goal",
  goalHint: (reward: number, goal: number) => `Earn +${reward} coins for ${goal} completions`,
  goalReachedTitle: "Daily goal reached",
  goalReachedHint: (reward: number) => `+${reward} coins earned today`,
  streakTitle: (n: number) => `${n}-day streak`,
  streakHint: "Show up tomorrow to keep it going",
  streakEmptyTitle: "No streak yet",
  streakEmptyHint: "Log a practice today to start one",
} as const;

export const CELEBRATION_STRINGS = {
  title: "Daily goal crushed!",
  subtitle: (n: number) => `You logged ${n} completions today.`,
  coinsLine: (n: number) => `+${n} coins`,
  dismiss: "Nice!",
  balanceLine: (total: number) => `Balance: ${total} coins`,
  badgeFirstMilestone: "1st milestone",
} as const;
